[package]
name = "oauth2_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
anyhow = "1.0.58"
base64 = "0.13.0"
dotenv = "0.15.0"
reqwest = { version = "0.11.11", features = ["json"] }
serde = {version="1", default-features = false, features=["derive"]}
serde_json = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
urlencoding = "2.1.0"
